// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "clockctrl1.h"

/////////////////////////////////////////////////////////////////////////////
// CClockctrl1

IMPLEMENT_DYNCREATE(CClockctrl1, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CClockctrl1 properties

/////////////////////////////////////////////////////////////////////////////
// CClockctrl1 operations
